CREATE TABLE Books (BookID int PRIMARY KEY NOT NULL IDENTITY(1,1), 
					BookName varchar(255) NOT NULL,
					Author varchar(255) NOT NULL,
					ISBN char(13) NOT NULL)

CREATE TABLE Users (UserID int PRIMARY KEY NOT NULL IDENTITY(1,1),
					Username varchar(255) NOT NULL)

CREATE TABLE Copies (CopyID int PRIMARY KEY NOT NULL IDENTITY(1,1),
					 BookID int NOT NULL FOREIGN KEY REFERENCES Books(BookID),
					 UserID int NULL FOREIGN KEY REFERENCES Users(UserID))


